config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :images
  resources :stories
  resources :users

  root 'stories#home'
  get  'login'   => 'session#new'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  post '/refresh' => 'stories#refresh'
  post 'stories/:id/publish' => 'stories#publish'

end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  title      :text
#  public     :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Story < ActiveRecord::Base
  belongs_to :user
  has_many :images
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  def home
    end

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    render :json => @stories.to_json(:include => [:images])
  end

  # GET /stories/1
  # GET /stories/1.json
  def show

  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @storyNew = @story.content.scan( /#(\w+)/ ).flatten
    @gifs = []

    respond_to do |format|
      if @story.save
        current_user.stories << @story if current_user.present? # Associate the story with the current user.
        @storyNew.each do |tag|

          # HANDLE NO SEARCH RESULTS! render :json => { status: :unprocessable_entity, reason: "No available image" }

          giphy_search = Giphy.search(tag, {limit: 1}) # Make a request to the Giphy API passing in the tag and the options
          # @gifs << giphy_search   # When that comes back, push the result into the @gifs array
          image = Image.create :url => giphy_search[0].original_image.url.to_s, :word => tag
          # Save the correct information as a new Image and associate it with the story
          @story.images << image
          # puts tag

        end
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :json => @story.to_json(:include => [:images]) }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end


  def publish
    story = Story.find params[:id]
    story.update :public => true
    render :json => { :status => 'ok'}
  end


  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def refresh
    image = Image.find_by :url => params[:image_url]
    res = Giphy.random(image["word"])
    
    image.url = res.image_original_url.to_s
    image.save

    render :json => image
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:content, :user_id, :title, :public)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<div id="main"></div>

<script type="html/template" id="appViewTemplate">

</script>

<div class="divViewShowTitle" class id="title">

      <h1>YOUR GIPHY GOSS</h1>

</div> 

<p>    </p>


<%= link_to 'Back to Gossip Gallery', root_url %> 

<h2 class="divViewShowOutputTitle">

<p>
  <%= @story.title %>
</p>

<span class="tag">
  <%= @story.content %>
</span>

</h2>

<p>
  <% @story.images.each do |g| %>
  
  <img src="<%= g.url %>">

  <%end%>

</p>


<script type="html/template" id="StoryViewTemplate">

    <div class="divViewShowShareButton">

      <button class="button">SHARE YOUR GOSS TO GOSSIP GALLERY</button>

    </div>
</script>

app/views/stories/home.html.erb
<body>
  
  <div class="homePageHeader" class id="title">


      <h2>Whats the goss?</h2>

  </div>

<div id="main"></div>

<script type="html/template" id="appViewTemplate">


<!-- Story and title input div -->

<div class="divNewView">

  <div id="storyForm" class="divNewViewInput">
    Form goes here.
  </div>

</script>

<script type="html/template" id="storyInputViewTemplate">

  <div class="divNewViewTitle" >
        <input class="input" type="text" placeholder="CREATE GIPHY GOSSIP TITLE" ></input>

        <textarea placeholder="Enter a story with #words to turn them into Giphy Goss!" class="input"></textarea>
  </div>

  <div class="divNewViewButton">

        <button class="button">CREATE STORY</button>

  </div>

</script>

<script type="html/template" id="StoryViewTemplate">

    <div class="divViewShowShareButton">

      <button class="button">SHARE YOUR GOSS TO GOSSIP GALLERY</button>


    </div>
</script>


 <!-- Result Output div view -->

<div class="divViewShow">

    <div class="divViewShowTitle" class id="title">

      <h1>YOUR GIPHY GOSS</h1>

    </div>

</div>

</div>

  <p id="myGoss"> </p>

  <!-- Giphy Gossip view -->

 <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56a07cf372312ad9" async="async"></script>

  <div class="divGiphyGossip">

      <div class="divGiphyGossipTitle" class id="title">
        <h1>GOSSIP GALLERY</h1>
      </div>

</div>

    <p id="stories"></p>

    <img src="https://raw.githubusercontent.com/cirla/vim-giphy/master/powered_by_giphy.gif" style="width:200px;height:42px;"/>

</body>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Title</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.content %></td>
        <td><%= story.user_id %></td>
        <td><%= story.title %></td>
        <td><%= story.public %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="divViewShowTitle" class id="title">

      <h1>YOUR GIPHY GOSS</h1>

</div>

<h2 class="divViewShowOutputTitle">

<p>
  <%= @story.title %>
</p>

<span class="tag">
  <%= @story.content %>
</span>

</h2>

<p>
  <% @story.images.each do |g| %>
  
  <img src="<%= g.url %>">

  <%end%>

</p>


<%= link_to 'Change your Giphy Gossip', root_url %> 